#!/bin/bash
# Bash script to run convert_videos under control of RVM (for cron).
# Runs from the installed gem, not the Git repo.
# 0  4  *  *  *  /Users/jdee/github/jdee/video_converter/rvm_convert_videos > /dev/null 2>&1

PATH=${PATH}:/usr/local/bin
export LANG=en_US.UTF-8

source ~/.rvm/scripts/rvm
rvm use default

# Pass options to convert_videos, e.g.
# rvm_convert_videos --no-clean
convert_videos $*
